packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  "@tanstack/react-query": ^5.59.15
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  lucide-react: ^0.451.0
  tailwindcss: ^3.4.13
  eslint: ^9.15.0
  prettier: ^3.3.3
  typescript: ^5.6.3
  "@types/node": ^20
  "zod": ^3.24.1
  "next": ^15.1.0
  "drizzle-orm": ^0.38.2

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^18.3.1
    "@types/react-dom": ^18.3.0
